[package]
name = "bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
itron = { version = "= 0.1.9", features = ["asp3", "nightly", "unstable"] }

[lib]
name = "itron"
crate-type = ["staticlib"]
