[package]
name = "ros2-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
r2r = "0.9.5"
futures = "0.3"

[features]
# Enable building binaries that depend on Autoware message packages present in the environment.
autoware_msgs = []
